version: "3.8"

services:
  db:
    image: mysql:8.0.34-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER:  aa 
      MYSQL_PASSWORD: zz
    ports:
        - "3306:3306"
    volumes:
     - database:/var/lib/mysql
    networks:
      dnd_network:

  admin-db:
    image: phpmyadmin:5.2.1-apache
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: "db"
    networks:
      dnd_network:

networks:
  dnd_network:

volumes:
  database:
